[PIN-3405] added route for updateVerifiedAttributeExtensionDate
pagopa/interop-be-tenant-process pull request #60
Opened 2023-05-23 10:26 UTC by AsterITA

2023-05-23 13:10 UTC, galales requested changes

2023-05-23 13:10 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/api/impl/TenantApiServiceImpl.scala
> +  ): Route = authorize(M2M_ROLE) {
```suggestion
  ): Route = authorize(INTERNAL_ROLE) {
```

2023-05-23 13:10 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/api/impl/TenantApiServiceImpl.scala
> +    val operationLabel = s"Update attribute ${attributeId} to tenant $tenantId"
```suggestion
    val operationLabel = s"Update extension date of attribute ${attributeId} for tenant $tenantId"
```

2023-05-23 13:10 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/error/ResponseHandlers.scala
> +      case Failure(ex)                                    => internalServerError(ex, logMessage)
```suggestion
      case Failure(ex: TenantByIdNotFound) => notFound(ex, logMessage)
      case Failure(ex)                                    => internalServerError(ex, logMessage)
```

2023-05-23 13:10 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/error/ResponseHandlers.scala
> +      case Failure(ex: ExpirationDateNotFoundInVerifier)  => notFound(ex, logMessage)
hits should probably be a bad request
```suggestion
      case Failure(ex: ExpirationDateNotFoundInVerifier)  => badRequest(ex, logMessage)
```

2023-05-23 13:10 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/api/impl/TenantApiServiceImpl.scala
> +      )
I know this should probably never happen, but could it be safe to default this to `expirationDate` value?

2023-05-23 13:10 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/error/ResponseHandlers.scala
> +      case Failure(ex: ExpirationDateCannotBeInThePast)   => badRequest(ex, logMessage)
I may missing it, but it seems this is not used in this endpoint
```suggestion
```

2023-05-23 13:10 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/api/impl/TenantApiServiceImpl.scala
> +                verificationDate = now,
`verificationDate` should not be updated, for a couple of reasons:
- the result of `Duration.between(oldVerifier.verificationDate, expirationDate)` would be not what we expect (it gets smaller approaching `expirationDate` and then raise over time)
- we would lose the information about when the attribute has been verified by the user

leaving to its original value should satisfy the requirement

2023-05-23 13:10 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/error/ResponseHandlers.scala
> +      case Failure(ex: ExtensionDateNotFoundInVerifier)   => notFound(ex, logMessage)
probably not required

2023-05-23 13:10 UTC, galales commented on src/main/resources/interface-specification.yml
> +          description: Tenant Not Found
The endpoint returns 404 also in case of missing attribute
```suggestion
          description: Not Found
```

2023-05-23 13:10 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/api/impl/TenantApiServiceImpl.scala
> +  ): Route = authorize(M2M_ROLE) {
may you add the authorization test for this endpoint?

2023-05-23 13:47 UTC, AsterITA commented on src/main/scala/it/pagopa/interop/tenantprocess/api/impl/TenantApiServiceImpl.scala
> +  ): Route = authorize(M2M_ROLE) {
By applying the `M2M_ROLE` it fails on `getOrganizationIdFutureUUID` because it can't find the organization claim, how can we fix this?

2023-05-23 13:51 UTC, galales commented on src/main/scala/it/pagopa/interop/tenantprocess/api/impl/TenantApiServiceImpl.scala
> +  ): Route = authorize(M2M_ROLE) {
if this endpoint is called by one of our jobs, there is no organization id in the token.
I guess that the verifier id should be passed as parameter

2023-05-26 10:51 UTC, galales approved these changes

2023-05-26 12:33 UTC, beetlecrunch approved these changes

2023-05-26 12:40 UTC, merged