[PIN-3443]Added support role to tenant process for the GET request
pagopa/interop-be-tenant-process pull request #61
Opened 2023-05-26 14:56 UTC by rGregnanin

2023-05-29 07:58 UTC, galales requested changes

2023-05-29 07:58 UTC, galales commented on src/test/resources/authz.json
I guess `getTenant` config is missing, may you add it?

2023-05-29 08:44 UTC, rGregnanin commented on src/test/resources/authz.json
Added `getTenant` config to `authz.json`

2023-05-29 09:59 UTC, galales approved these changes

2023-05-31 08:27 UTC, beetlecrunch approved these changes

2023-05-31 08:57 UTC, merged